# Generated by Django 5.2.4 on 2025-08-03 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wellbeing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='academic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wellbeing',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wellbeing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
